#production:
#  adapter: postgresql
#  username: postgres
#  password:
#  pool: 5
#  host: 172.17.0.2
#  database: ruptiva_production
#
#development:
#  adapter: postgresql
#  username: postgres
#  password:
#  host: 172.17.0.2
#  pool: 5
#  database: ruptiva_development
#
#test:
#  adapter: postgresql
#  username: postgres
#  password:
#  host: 172.17.0.2
#  database: ruptiva_test

production:
  adapter: postgresql
  username: <%= ENV.fetch('DB_USERNAME') { 'user' } %>
  password: <%= ENV.fetch('DB_PASSWORD') { 'password' } %>
  pool: 5
  host: <%= ENV.fetch('DB_HOST') { 'localhost' } %>
  database: ruptiva_production

development:
  adapter: postgresql
  username: <%= ENV.fetch('DB_USERNAME') { 'user' } %>
  password: <%= ENV.fetch('DB_PASSWORD') { 'password' } %>
  pool: 5
  host: <%= ENV.fetch('DB_HOST') { 'localhost' } %>
  database: ruptiva_development

test:
  adapter: postgresql
  username: <%= ENV.fetch('DB_USERNAME') { 'user' } %>
  password: <%= ENV.fetch('DB_PASSWORD') { 'password' } %>
  pool: 5
  host: <%= ENV.fetch('DB_HOST') { 'localhost' } %>
  database: ruptiva_test